import Config

# Configure your database
config :hedgehog, Hedgehog.Repo,
  database: Path.expand("../hedgehog_dev.db", Path.dirname(__ENV__.file)),
  pool_size: 5,
  show_sensitive_data_on_connection_error: true,
  load_extensions: [
    Path.expand("./priv/sqlite/litestream.so", __DIR__)
  ]

litestream_endpoint =
  System.get_env("LITESTREAM_ENDPOINT") ||
    raise """
    environment variable LITESTREAM_REPLICA_URL is missing.
    For example: s3://hedgehog/db?endpoint=<account-id>.r2.cloudflarestorage.com
    """

config :hedgehog, Hedgehog.Litestream,
  enabled: true,
  repo: Hedgehog.Repo,
  strategy: %{
    endpoint: litestream_endpoint,
    bucket: "hedgehog",
    path: "my_backup",
    region: "auto",
    # override_architecture: :x86_64,
    access_key_id: System.fetch_env!("LITESTREAM_ACCESS_KEY_ID"),
    secret_access_key: System.fetch_env!("LITESTREAM_SECRET_ACCESS_KEY")
  }

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :hedgehog, HedgehogWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ey1/23ez5+WeFYJDiPJhw87mQNmkrP5dhZQ32kIF9eNuJZfnH4NfZCQY1tokQY/n",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:hedgehog, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:hedgehog, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :hedgehog, HedgehogWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/hedgehog_web/router\.ex$"E,
      ~r"lib/hedgehog_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :hedgehog, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, level: :info
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
